### ISSUE TITLE
No check your email page?

### ISSUE THREAD

**Issue by delboy1978uk** [hrevert/HtUserRegistration#25]
After registering and the activation email is sent out, I am taken back to /user/login
There is no mention of an email having been sent, and there is a form error, so it looks like it is still trying to log you in!
There is an option for post_verification_route, but I think this module should also have a view for createRegistrationRecord.post, saying "Go check your email for a link to activate your account".
Your thoughts?

**Comment by ojhaujjwal** [comment]
That seems good but this module is designed to be as simple as possible so that it will be useful for most use cases. All this module does is that it listens to `register.post` event and sends the email. If you want something more than that, you need to override the zfcuser controller to fit your needs.

**Comment by delboy1978uk** [comment]
ok, however i cant listen for an event with the mail being sent, although i see an event being triggered for createRegistrationRecord. obviously though that happens before the actual email, so it would be nice to have an sendVerificationEmail event :-) Can do it for you if you like!
